### ISSUE TITLE
Retry logic doesn't handle maxRetries threshold properly

### ISSUE THREAD

**Issue by rkarveshkin** [fent/node-miniget#31]
Whole logic hangs once a server responses with 429 code more then maxRetries
159 line:
https://github.com/fent/node-miniget/blob/master/src/index.ts#L159
Сould be rewritten like this:
if (retries < opts.maxRetries) {
	doRetry({ retryAfter: parseInt(res.headers['retry-after'], 10) });
} else {
	let err = Error('Status code: ' + res.statusCode);
	stream.emit('error', err);
}

**Comment by fent** [comment]
retry is handled separately from a reconnect. do you know if this happens at the beginning of a download, or the middle?

sorry for late response
