### ISSUE TITLE
'Request path contains unescaped characters'

### ISSUE THREAD

**Issue by ZoroSC** [fent/node-miniget#4]
This is the link to the error it self https://hastebin.com/epogesaloz.tex, I am trying to play a live video from YouTube. I never had this issue before with it. Not sure why its doing it now.

**Comment by ZoroSC** [comment]
I am using ytdl-core and I got that error with miniget

**Comment by ZoroSC** [comment]
`stream = ytdl("https://www.youtube.com/watch?v=" + id, {
            filter: 'audioonly'
        });` This is the code I had but I changed it to `stream = ytdl("https://www.youtube.com/watch?v=" + id, {audioonly: true})` And it now plays live videos.

**Comment by fent** [comment]
It happens with some audio only live streams https://github.com/fent/node-ytdl-core/issues/231
