### ISSUE TITLE
Error Status Code 429

### ISSUE THREAD

**Issue by BlazeDexX** [fent/node-miniget#49]
# Can you fix it?
I get error from here 

![image](https://user-images.githubusercontent.com/67855694/95005574-9434a700-0624-11eb-8194-320d86f76068.png)

**Comment by Roki100** [comment]
It is not a miniget bug, it seems the service you are making requests to is ratelimiting you for making too many requests in a short period of time

**Comment by fent** [comment]
are you using ytdl-core? https://github.com/fent/node-ytdl-core/issues/635

**Comment by BlazeDexX** [comment]
yes, but now the service has been running now
