### ISSUE TITLE
Error: input stream: Status code: 403

### ISSUE THREAD

**Issue by gdsasa** [fent/node-miniget#51]
![Captura](https://user-images.githubusercontent.com/69827079/98309515-f3daf500-1fca-11eb-8133-abe05d194d87.PNG)
Any solution to this?

**Comment by fent** [comment]
it's the status code from the requested url

**Comment by gdsasa** [comment]
How to solve it?

**Comment by fent** [comment]
403 means access denied. check the request you made has the correct path/params/etc
