### ISSUE TITLE
Passing options into underlying http lib

### ISSUE THREAD

**Issue by stoically** [fent/node-miniget#52]
Currently it isn't supported to pass arbitrary options into the underlying http calls like `http.get`. It'd be nice if there were a way to do that.

**Comment by fent** [comment]
huh? you can pass any options that you can normally pass to `http.get`, it's right there in the readme on the first line -_-

https://github.com/fent/node-miniget#minigeturl-options

**Comment by stoically** [comment]
Oh, my bad, not sure how I missed that. Sorry for wasting your time and thanks for your hard work (especially on ytdl-core)!

**Comment by fent** [comment]
no problem!
