### ISSUE TITLE
How use miniget with proxy ?

### ISSUE THREAD

**Issue by Murena7** [fent/node-miniget#56]
Hi all - is possible use miniget with proxy ? Please describe how i can do this ? Thanks

**Comment by fent** [comment]
hi. i must've missed this, sorry for replying so late. it's best to use an agent to handle proxies https://www.npmjs.com/package/proxy-agent

you can then pass the agent to miniget
```js
miniget(url, { agent: new ProxyAgent(proxyUri) })
```
