### ISSUE TITLE
Support for http.get Option?

### ISSUE THREAD

**Issue by Yonle** [fent/node-miniget#59]
Could you add a support for http.get Option?

I want it works like this:
```js
miniget({
  hostname: "github.com",
  headers: {
    // ....
  }
});
```

**Comment by redbrain** [comment]
Pretty sure you can already do this. Look at this line from the README:
> `options` can have any properties from the [`http.request()` function](https://nodejs.org/api/http.html#http_http_request_options_callback)

**Comment by Yonle** [comment]
Nope
![Screenshot_2021_0515_214401](https://user-images.githubusercontent.com/63401712/118363380-b7660280-b5c6-11eb-9b84-645b419fa4db.png)

**Comment by Yonle** [comment]
Bypass Momento.

```javascript
miniget("", {
  hostname: "github.com",
  path: "/fent"
}).pipe(....);
```

**Comment by TimeForANinja** [comment]
can not replicate with the code snipped you provided
can you provide npm & package version?

**Comment by Yonle** [comment]
Tried Code:
```js
miniget({
  hostname: "localhost",
  port: 3000
});
```

Miniget v4.2.0

**Comment by TimeForANinja** [comment]
> Tried Code:
> 
> ```js
> const miniget = require("miniget");
> 
> miniget({
>   hostname: "localhost",
>   port: 3000
> });
> ```
> 
> Miniget v4.2.0

that's simply not enough information to represent a full url
![image](https://user-images.githubusercontent.com/17046330/118409656-cf538a00-b68b-11eb-8895-b381757d67dc.png)
from the original rfc 3986...
at least scheme and authority are required
authority is hostname/ip + port (also known as hostname)
and scheme is more commonly known as protocol

some attributes like port & path have default values... but they might depend on other attributes (e.g. default port depends on protocol)

for your use-case it should be enough to add protocol...
