### ISSUE TITLE
Support webpacking

### ISSUE THREAD

**Issue by redbrain** [fent/node-miniget#62]
miniget appears to fail in webpacked environments (see fent/node-ytdl-core#919).
While miniget is written for node, it would be nice to have an edge case so it doesn't fail when webpacked.
One way to do this could be passing all arguments though to `fetch()` if a browser is detected.

Willing to write a PR to close this issue once the best course of action is decided.

**Comment by TimeForANinja** [comment]
guess this is also related to https://github.com/TimeForANinja/node-ytsr/issues/137
shouldn't the webpacking process include polyfilling http and https?

**Comment by redbrain** [comment]
My webpack config might somehow be skipping those polyfills, though I'm not sure how.
I'll toy more with webpack sometime in the next few weeks and see if I can get it to work.
If you have the time, it would be wonderful if you could find a resolution as well.
