### ISSUE TITLE
TypeError: destroyArgs is not iterable (cannot read property undefined)

### ISSUE THREAD

**Issue by pro-sumer** [fent/node-miniget#68]
Sometimes one of my [node-feedsub](https://github.com/fent/node-feedsub) based scripts fails with this error:

```
Oct 29 04:27:53 pi-hb op-run[22098]: /home/me/Developer/my-script/node_modules/.pnpm/miniget@4.2.2/node_modules/miniget/dist/index.js:243
Oct 29 04:27:53 pi-hb op-run[22098]:             streamDestroy(...destroyArgs);
Oct 29 04:27:53 pi-hb op-run[22098]:                              ^
Oct 29 04:27:53 pi-hb op-run[22098]: TypeError: destroyArgs is not iterable (cannot read property undefined)
```

Would it be possible to add some defensive programming here to prevent this crash?

**Comment by fent** [comment]
hello, what environment or node version are you running?

**Comment by pro-sumer** [comment]
By now it's Node v19.7.0 on macOS Ventura.

**Comment by fent** [comment]
if you can consistently reproduce this, would you mind editing this line

https://github.com/fent/node-miniget/blob/master/src/index.ts#L305

to 

```
  let destroyArgs: any[] = [];
```

and see if it still happens

**Comment by pro-sumer** [comment]
Sorry, forgot to add this to my todo list when you replied...

In my project that was suffering from this I migrated from `node-feedsub` to [rss-url-parser](https://github.com/AlexChesters/rss-url-parser) and continued development. I'm not sure whether I can easily revert without breaking (my) newer code.

I'm still using `node-feedsub` in two other projects. In those I have not run into this problem (without the suggested modification).
