### ISSUE TITLE
SSRF Vulnerability in request function

### ISSUE THREAD

**Issue by LightYagami28** [fent/node-miniget#74]
**Issue Description:**
A potential Server-Side Request Forgery (SSRF) vulnerability was detected in the `miniget` library. The issue was identified in the file `index.js` at line 170, where unsanitized input from the document location flows into a request.

**Steps to Reproduce:**
This vulnerability was detected using Snyk Code analysis. The code in question does not adequately validate or sanitize the input, leading to a potential SSRF risk.

**Suggested Fix:**
It is recommended to validate the input URL, potentially by implementing a whitelist of allowed domains or by sanitizing user input before making the request.

**References:**
- [Snyk Documentation on SSRF](https://docs.snyk.io/learn/security-vulnerabilities/server-side-request-forgery)

**Comment by LightYagami28** [comment]
I made a pull request soon with the fix @fent

**Comment by LightYagami28** [comment]
Pls fix @fent

**Comment by fent** [comment]
The link doesn't work. what's the suggested fix for this?

**Comment by LightYagami28** [comment]
New link: https://learn.snyk.io/lesson/ssrf-server-side-request-forgery/

**Comment by fent** [comment]
so the suggested fix is to not allow common internal domains such as `localhost`, `127.0.0.1`, `192.....`, etc? although there could be a custom internal domain

i also looked at other http libraries like got, node-fetch, superagent, and request. only request mitigates around this by not allowing redirects for non-GET requests [here](https://github.com/request/request/blob/3c0cddc7c8eb60b470e9519da85896ed7ee0081e/lib/redirect.js#L56-L63)
